@startmindmap
title 定价列表

+_ PriceList
++_ BaseBreadcrumb
++_ BasePagination
++_ PriceForm
++_ ProceAll

@endmindmap

@startmindmap
title 报价列表

+_ QuotationList
++_ BasePagination
++_PurchaseForm
++ViewForm
++_ PriceForm

@endmindmap